# Generated by Django 6.1.1 on 2026-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reports',
            field=models.IntegerField(null=True),
        ),
    ]
