# Generated by Django 6.1.1 on 2026-09-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
